export let conditions = {
    '1': 'id',
    '836': 'Herpes zoster',
    '1210': 'Parotid enlargement, persistent unexplained',
    '2575': 'Angular cheilitis',
    '2576': 'Oral ulcerations, recurrent',
    '2891': 'Lineal gingival erythema',
    '5012': 'Respiratory tract infections, recurrent (sinusitis, tonsilitus, otitis media, pharyngitis)',
    '5327': 'Asymptomatic HIV infection',
    '5328': 'Persistent generalized lymphadenopathy',
    '6775': 'Wart virus infection, extensive',
    '6776': 'Molluscum contagiosum, extensive',
    '7536': 'Papular pruritic eruptions / Fungal nail infections',
    '7537': 'Hepatosplenomegaly, persistent unexplained',
    '836': 'Herpes zoster',
    '1215': 'Bacterial pneumonia, severe recurrent',
    '2575': 'Angular cheilitis',
    '2576': 'Oral ulcerations, recurrent',
    '2578': 'Seborrhoeic dermatitis',
    '2582': 'Anaemia, unexplained < 8 g/dl',
    '2889': 'Chronic HIV-associated lung disease, including bronchiectasis',
    '5012': 'Respiratory tract infections, recurrent (sinusitis, tonsilitus, otitis media, pharyngitis)',
    '5024': 'Symptomatic lymphoid interstitial pneumonia',
    '5027': 'Fever, persistent unexplained, intermittent or constant, >1 month',
    '5332': 'Moderate weight loss less than or equal to 10 percent, unexplained',
    '5337': 'Oral hairy leukoplakia',
    '7038': 'Unspecified stage 2 condition',
    '7536': 'Papular pruritic eruptions / Fungal nail infections',
    '7539': 'Tuberculosis (PTB or EPTB) within the last 2 years',
    '7543': 'Moderate unexplained wasting/malnutrition not responding to treatment (weight-for-height/ -age 70-79% or muac 11-12 cm)',
    '7544': 'Diarrhoea, persistent unexplained (14 days or more)',
    '7545': 'Oral candidiasis (from age 2 months)',
    '7546': 'Acute necrotizing ulcerative gingivitis or periodontitis',
    '7547': 'Lymph node tuberculosis',
    '7954': 'Neutropaenia, unexplained < 500 /mm(cubed)',
    '7955': 'Thrombocytopaenia, chronic < 50,000 /mm(cubed)',
    '8206': 'Pulmonary tuberculosis (current)',
    '507': 'Kaposis sarcoma',
    '882': 'Pneumocystis pneumonia',
    '1362': 'HIV encephalopathy',
    '1547': 'Extrapulmonary tuberculosis (EPTB)',
    '2582': 'Anaemia, unexplained < 8 g/dl',
    '2585': 'Disseminated non-tuberculosis mycobacterial infection',
    '2587': 'Cerebral or B-cell non Hodgkin lymphoma',
    '2894': 'Bacterial infections, severe recurrent  (empyema, pyomyositis, meningitis, bone/joint infections but EXCLUDING pneumonia)',
    '3068': 'Severe unexplained wasting or malnutrition not responding to treatment (weight-for-height/ -age <70% or MUAC less than 11cm or oedema)',
    '5018': 'Diarrhoea, chronic (>1 month) unexplained',
    '5027': 'Fever, persistent unexplained, intermittent or constant, >1 month',
    '5046': 'Progressive multifocal leukoencephalopathy',
    '5048': 'Toxoplasmosis of the brain (from age 1 month)',
    '5334': 'Oral candidiasis',
    '5337': 'Oral hairy leukoplakia',
    '5340': 'Candidiasis of oseophagus, trachea and bronchi or lungs',
    '6408': 'Other',
    '7039': 'Unspecified stage 3 condition',
    '7539': 'Tuberculosis (PTB or EPTB) within the last 2 years',
    '7540': 'Severe weight loss >10% and/or BMI <18.5kg/m^2, unexplained',
    '7541': 'Severe bacterial infections (pneumonia, empyema, pyomyositis, bone/joint, meningitis, bacteraemia)',
    '7548': 'Cryptococcal meningitis or other extrapulmonary cryptococcosis',
    '7549': 'Cryptosporidiosis, chronic with diarroea',
    '7550': 'Disseminated mycosis (coccidiomycosis or histoplasmosis)',
    '7552': 'Cytomegalovirus infection: rentinitis or other organ (from age 1 month)',
    '7954': 'Neutropaenia, unexplained < 500 /mm(cubed)',
    '7955': 'Thrombocytopaenia, chronic < 50,000 /mm(cubed)',
    '7956': 'Isosporiasis >1 month',
    '7957': 'Symptomatic HIV-associated nephropathy or cardiomyopathy',
    '7960': 'Chronic herpes simplex infection (orolabial or cutaneous >1 month or visceral at any site)',
    '7961': 'Recto-vaginal fistula, HIV-associated',
    '8205': 'Hepatitis B or C infection',
    '8206': 'Pulmonary tuberculosis (current)',
    '507': 'Kaposis sarcoma',
    '882': 'Pneumocystis pneumonia',
    '1215': 'Bacterial pneumonia, severe recurrent',
    '1547': 'Extrapulmonary tuberculosis (EPTB)',
    '2583': 'Toxoplasmosis of the brain',
    '2587': 'Cerebral or B-cell non Hodgkin lymphoma',
    '2588': 'Invasive cancer of cervix',
    '5340': 'Candidiasis of oseophagus, trachea and bronchi or lungs',
    '5344': 'Chronic herpes simplex infection (orolabial, gential / anorectal >1 month or visceral at any site)',
    '6408': 'Other',
    '7040': 'Unspecified stage 4 condition',
    '7548': 'Cryptococcal meningitis or other extrapulmonary cryptococcosis',
    '7551': 'Cytomegalovirus infection (retinitis or infection or other organs)',
    '7957': 'Symptomatic HIV-associated nephropathy or cardiomyopathy',
    '7959': 'Non-typhoidal Salmonella bacteraemia, recurrent'
  };